name: 'PHSA Configuration'
description: 'Standard configuration to be managed across PHSA sites.'
type: module
core_version_requirement: '^9.4 || ^10'
dependencies:
  - 'addtoany:addtoany'
  - 'crop:crop'
  - 'drupal:ckeditor5'
  - 'drupal:content_moderation'
  - 'drupal:editor'
  - 'drupal:field'
  - 'drupal:file'
  - 'drupal:filter'
  - 'drupal:image'
  - 'drupal:language'
  - 'drupal:node'
  - 'drupal:path'
  - 'drupal:system'
  - 'drupal:user'
  - 'drupal:views'
  - 'features:features'
  - 'focal_point:focal_point'
  - 'metatag:metatag'
  - 'oembed_providers:oembed_providers'
  - 'phsa_media_server:phsa_media_server'
  - 'scheduler:scheduler'
  - 'tooltip:tooltip'
  - 'webform:webform'
package: 'PHSA Core'
